### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by dkremniov-bc** [zeta-chain/universalkit#26]
Hey, is this project production ready? I saw hardcoded references to testnet in Bitcoin wallet connectors (e.g. in `/src/providers/BitcoinWalletProvider/okx.ts`), and was wondering about the status of this project.

According to official docs, this should be used for testnet only but this repo doesn't mention anything about it, so not sure how up to date that is.
> The component library is in under active development and currently is recommended for testnet use only.

**Comment by fadeev** [comment]
@dkremniov-bc this project hasn't been battle-tested on mainnet, but you can use it as a starting point to make a production ready app.
